-- DO NOT EDIT THIS FILE --
local _, AmakHealsTextures = ...
if AmakHealsTextures.BuildFail(80000) then
	print("AmakHealsTextures", "Failed to Load")
	return
else
	AmakHealsTextures.print("Successfully Loaded")
end
-- DO NOT EDIT THIS FILE --
